baseURL = "https://careersosimple.com/"
languageCode = "en"
title = "Career So Simple"
theme = "hugo-initio"

[params]
    name = "Career So Simple"
    description = "Making students complex career decisions so simple!"
    email = ""
    phone = ""
    address = ""
    year = 2021
    avatar = "images/official-logo.png"
    avatarclass = "circle"
    background = ""
    banner = ""
    favicon = "images/icon.png"
    DateForm = "January 2, 2006"
    author = "Aaron Dendero"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownloads = true
    showClients = true

    showFooterContact = false
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
#[[menu.main]]
#    name = "Blog"
#    url = "/post/"
#    weight = 5

[params.disqus]
    site = ""

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/careersosimple/"
    icon = "fab fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/careersosimple"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/aaron-dendero-10a5701aa/"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "email"
	url = "mailto:some.email@somewhere.com"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"